### ISSUE TITLE
Getting facts if nothing's changed

### ISSUE THREAD

**Issue by ahamilto156** [HarryHarcourt/Ansible-RHEL8-CIS-Benchmarks#3]
G'day Harry,

BTW: Thx for writing this role, I use it extensively and have credited you in my credits...

This is more an RFE, than a bug or issue, and it's just to make the whole CIS benchmark run faster. If a task is skipped, the facts might still be unnecessarily refreshed. e.g.
TASK [Ansible-RHEL8-CIS-Benchmarks : 1.1.14 - Ensure nodev option set on /home partition] ***************************
skipping: [server.local] => (item={'mount': '/', 'device': '/dev/mapper/rhel-root', 'fstype': 'xfs', 'options': 'rw,seclabel,relatime,attr2,inode64,noquota', 'size_total': 38476525568, 'size_available': 35744559104, 'block_size': 4096, 'block_total': 9393683, 'block_available': 8726699, 'block_used': 666984, 'inode_total': 18796544, 'inode_available': 18738753, 'inode_used': 57791, 'uuid': '7b207674-3a3b-4b80-9de3-ba808846ae07'}) 
skipping: [server.local] => (item={'mount': '/boot', 'device': '/dev/vda1', 'fstype': 'xfs', 'options': 'rw,seclabel,relatime,attr2,inode64,noquota', 'size_total': 1063256064, 'size_available': 812662784, 'block_size': 4096, 'block_total': 259584, 'block_available': 198404, 'block_used': 61180, 'inode_total': 524288, 'inode_available': 523980, 'inode_used': 308, 'uuid': '14db2aba-53cf-4e2d-b8a7-77710eec3748'}) 

TASK [Ansible-RHEL8-CIS-Benchmarks : Refresh facts] *****************************************************************
ok: [server.local]

Whether it's worth the effort to put the conditionals in the code, is debatable, but I thought I would message you on it.

**Comment by HarryHarcourt** [comment]
Hi, as I have not worked on this for a while (as I am sure you can tell), how would you go about addressing this?

**Comment by ahamilto156** [comment]
Harry,

Thx for the quick response, particularly as you haven't worked on it for a
while.

I've just *really* thought about it, and considering the gathering of facts
is automatic
<https://docs.ansible.com/ansible/latest/modules/setup_module.html >,
changing the conditional on gathering facts might well be impossible. I
don't believe it's worth the slight efficiency gain, to delve in *very*
deeply into Ansible to fix it, if it is at all possible.

Sorry to have bothered you. Feel free to close this "RFE!"

*NOTE:*
I'm sure you're aware of the nature of fact gathering, hence your
question...

Cheers,

Andrew Hamilton MEngSc. (Elec.), Grad Dip. PM, BE (Comp.)

Senior Consultant

Red Hat <https://www.redhat.com>

A: L11, 40 Marcus Clarke Street,

    Canberra City, ACT, 2601, Australia

E: andrew.hamilton@redhat.com <andrew.hamilton@redhat.com>
M: +61-477-242-645-[+61-477-ahamil]

F: +61-2-6247-4380
@RedHat <https://twitter.com/redhat>   Red Hat
<https://www.linkedin.com/company/red-hat>  Red Hat
<https://www.facebook.com/RedHatInc>
<https://red.ht/sig>

**Comment by HarryHarcourt** [comment]
Many thanks for the feedback, I will close this one (but remember it)

**Comment by ahamilto156** [comment]
Thx heaps.

Regards,

Andrew Hamilton MEngSc. (Elec.), Grad Dip. PM, BE (Comp.)

Senior Consultant

Red Hat <https://www.redhat.com>

A: L11, 40 Marcus Clarke Street,

    Canberra City, ACT, 2601, Australia

E: andrew.hamilton@redhat.com <andrew.hamilton@redhat.com>
M: +61-477-242-645-[+61-477-ahamil]

F: +61-2-6247-4380
@RedHat <https://twitter.com/redhat>   Red Hat
<https://www.linkedin.com/company/red-hat>  Red Hat
<https://www.facebook.com/RedHatInc>
<https://red.ht/sig>
